#:schema https://schemas.spinframework.dev/spin/manifest-v2/latest.json

spin_manifest_version = 2

[application]
name = "cat-validator"
version = "0.1.0"
authors = ["Thorsten Hans <thorsten.hans@fermyon.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "cat-validator"

[component.cat-validator]
source = "target/wasm32-wasip1/release/cat_validator.wasm"
allowed_outbound_hosts = []
key_value_stores = ["default"]

[component.cat-validator.build]
command = "cargo build --target wasm32-wasip1 --release"
watch = ["src/**/*.rs", "Cargo.toml"]
